# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudeep Saurabh
title: Cloud Engineering & Devops
email: sudeepsaurabhss@gmail.com
# email_title: Email (Email title override)

website: sudeepsaurabh.com
# website_title: Website (Website title override)
# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username: SuTiger19
linkedin_username: sudeep-saurabh19

# Additional icon links
#additional_links:
#- title: Link name
# icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profic_photo.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sudeep Saurabh. I am a software engineer with a solid background in cloud & web development. I am 4x AWS Certified and 2x HashiCrop-Terraform Certified.  I have experience in DevOps and cloud engineering, and I am eager to further my career in these fields. I am proud to have earned gold medals in the prestigious national and state-level competitions, Skills Canada 2024 and Skills Ontario 2024. 

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Consulate General of India
        sub_title: Software Engineer Intern
        caption: 09/2024 to Present
        additional_links: https://www.cgitoronto.gov.in/
        quote: >
          Leveraging automation and scripting expertise to enhance operational efficiency and data management at the Consulate General of India in Toronto.
        description: >
          At the Consulate General of India in Toronto, I streamlined data management by automating repetitive processes. I developed PowerShell scripts to download Excel files automatically, eliminating hours of manual work. Once the data was downloaded, I used Excel macros to clean, organize, and format it into ready-to-use tables for reporting. Additionally, I contributed to a simplified internal website to ensure smooth data access and visualization, reducing dependency on manual reporting and improving workflow efficiency. This combination of automation and user-friendly tools significantly enhanced data accuracy and sharing across departments.

      - layout: left
        title: Seneca Hackathon
        sub_title: Team Lead and Developer (Volunteer Experience)
        caption: 10/2024 to Present
        additional_links: https://www.senecahackathon.com
        quote: >
          Driving innovation and collaboration as part of the Seneca Hackathon organization, delivering impactful digital solutions.
        description: >
          As part of the Seneca Hackathon team, I took on the challenge of managing technical and organizational aspects. I worked closely with the team to gather requirements and map out plans that made sense for everyone involved. My main project was creating a website using Next.js for the frontend and Node.js for backend integration. The goal was to make the platform easy to use and accessible, ensuring everything—from registrations to updates—ran smoothly. It’s been rewarding to see how the platform brought the event to life.

      - layout: left
        title: AVM Services
        sub_title: Web Developer and Administrator
        caption: 07/2023 to 06/2024
        additional_links:
          - title: Company Website
            icon: fab fa-building
            url: []
        quote: >
          AVM Services specializes in providing Total Facility Management Services in India across sectors such as Corporate, Industrial, Retail, and Hospitality, ensuring exceptional quality, reliability, and customer satisfaction.
        description: >
          At AVM Services, I built a full-stack digital platform to modernize service booking management. Using Go for the backend and Angular for the frontend, I created a system that allowed users to book and manage services seamlessly. The platform replaced outdated processes like manual paperwork and scattered spreadsheets, leading to faster operations, a reliable user experience, and streamlined workflows for both the company and its clients.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Seneca Polytechnic
        sub_title: Project Management - Information Technology
        caption: May 2024- Dec 2024
        quote: >

        description: | # this will include new lines to allow paragraphs
          Currently part of Project Management Pogram at Seneca. This program taught me when to apply various IT methodologies, including Scrum and Agile, and refined my project management skills. Coursework included IT project management fundamentals, business systems environments, systems development, project leadership, finance, advanced IT project management, contract law, ethics, quality assurance, and case studies. It also offered an optional work term for practical experience in the IT sector.
      - layout: left
        title: Seneca Polytechnic
        sub_title: Cloud Architecture & Administration
        caption: Sep 2023 - April 2024
        quote: >
        description: | # this will include new lines to allow paragraphs
          I was part of  Cloud Architecture & Administration program in Seneca. I gained hands-on experience with Terraform and Ansible, studied cloud infrastructure and architecture for both Azure and AWS, and learned data storage, ethics, compliance, and risk management. My coursework included security management, focusing on Zero Trust Architecture, and a capstone project on migrating systems from on-premises to AWS. I also studied hybrid cloud integration with Azure, Docker and Kubernetes, project management tools, and incident response and forensics.
      - layout: left
        title: Delhi Technological University
        sub_title: B.Tech  Electronics & Communication Engineering
        caption: Aug 2019 - June 2023
        quote: >
          Delhi Technological University (DTU), formerly Delhi College of Engineering (DCE) is a state university in Rohini, Delhi, India. It was established in 1941 as Delhi Polytechnic. It consider as Tier 1 Universities , rank among top Engineering Universities in India.
        description: | # this will include new lines to allow paragraphs
          I have gotten a BTech in Electronics and Communication Engineering, where I gained a solid foundation in both theoretical and practical aspects of the field. My coursework covered electronic instrumentation, analog and digital electronics, signal processing, communication systems, and embedded systems. I developed skills in designing and analyzing electronic circuits, implementing communication protocols, and programming microprocessors.

  - title: Achievements
    layout: list
    content:
      - layout: left
        title: Gold Medal
        sub_title: Skills Canada

        caption: 2024
        description: | # this will include new lines to allow paragraphs
          After winning the Skills Ontario competition, I was given the opportunity to represent Team Ontario in a Cloud Computing contest. This event, held in an AWS cloud environment, featured a two-day AWS Jam with eight challenges each day, focusing on Solution Architecture and DevOps. The competition tested our ability to design scalable, secure, and high-availability web applications, emphasizing automation, network security, and monitoring. I successfully completed all challenges and am proud to say I won gold in this event as well.
          <div style="display: flex; justify-content: space-between;">
              <img src="images\SkillsCanadaWinning.png" alt="Photo 1" style="width: 30%;"/>
              <img src="images\WinningCircle.jpg" alt="Photo 2" style="width: 30%;"/>
              <img src="images\LastDaySkillsCanada.jpeg" alt="Photo 3" style="width: 30%;"/>
          </div>
      - layout: left
        title: Gold Medal  
        sub_title: Skills Ontario
        caption: 2024
        description: | # this will include new lines to allow paragraphs
          I  competed in a cloud computing contest focused on developing IT infrastructure in a AWS cloud environment. The competition was based on AWS Jam, where participants tackled technical challenges across various domains like security, DevOps, and data analytics.  I completed 8 challenges without using any clues, all within 45 minutes, and won the gold medal, showcasing my expertise in cloud computing.
          <div style="display: flex; justify-content: space-between;">
              <img src="images\SkillsOn.png" alt="Photo 1" style="width: 30%;"/>
              <img src="images\SkillsOntario_Prof.jpeg" alt="Photo 2" style="width: 30%;"/>
              <img src="images\Skill Ontario Time.png" alt="Photo 3" style="width: 30%;"/>
          </div>


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border:
          weak # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: Full-Stack DevOps Implementation with CI/CD and Cloud Services
        link: https://github.com/SuTiger19/Full-Stack-DevOps-Implementation-with-CICD-and-Cloud-Services
        link_text: github/SuTiger19
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/SuTiger19/Full-Stack-DevOps-Implementation-with-CICD-and-Cloud-Services

        quote: >
          This project demonstrates a comprehensive CI/CD pipeline that manages the full lifecycle of a Flask application—from image creation using GitHub Actions to deployment on Amazon Web Services (AWS) serivces (EKS and ECS) using Docker, Kubernetes, and Terraform.
        description: | # this will include new lines to allow paragraphs
          I implemented continuous integration (CI/CD) using GitHub Actions to automate testing and Docker image creation for a Flask application that was split between the front-end and a SQL back-end. Additionally, I leveraged Terraform for provisioning AWS EC2 instances, configuring Docker environments, and managing Kubernetes clusters via Kind for local testing and AWS EKS for production deployment. 
          The application was deployed on AWS ECS as well with Fargate to ensure scalable application deployment, while AWS RDS was used for database management, ensuring high availability and security.

      - layout: left
        border:
          weak # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: Full-Two-Tier DevOps Project with Ansible and Terraform
        link: https://github.com/SuTiger19/Two-Tier-Devops-Project-with-Ansible-and-Terrafrom
        link_text: github/SuTiger19
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/SuTiger19/Two-Tier-Devops-Project-with-Ansible-and-Terrafrom

        quote: >
          Deployed a scalable, secure AWS infrastructure for web applications using Terraform, Ansible, and AWS services.
        description: | # this will include new lines to allow paragraphs
          I designed and deployed a resilient AWS infrastructure using Terraform, incorporating an Application Load Balancer (ALB), Auto Scaling Groups (ASG), NAT Gateway, and Bastion Host to ensure scalability and secure access. 
          I automated the deployment of a web application on EC2 instances using Ansible, integrating content delivery from S3 buckets. Additionally, I implemented state locking with AWS DynamoDB to manage concurrency and ensure consistent infrastructure updates.

      - layout: left
        border:
          weak # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: Helping Local Businesses by using IoT Embedded Systems
        link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=iAZwHkEAAAAJ&citation_for_view=iAZwHkEAAAAJ:u5HHmVD_uO8C
        link_text: github/SuTiger19
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/ritlo/iot-business
        quote: >
          Final Year B.Tech Project. In these project we build protype to help local business around India to implemention technology without having worry about risky investment.
        description: |
          Designed and developed an IoT Embedded System for automatically collecting information from business locations such as customer traffic and demographics and uploading the collected information to a database which displays an overview of all businesses connected to the system. 
          I have also developed an Android app client which displays the collected information of the day, and receives alarm notifications from the location’s security systems.

  # - title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
